name: Arduino Library CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - arduino:avr:uno
          - arduino:renesas_uno:unor4wifi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install board cores
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli core install arduino:renesas_uno

      - name: Compile all examples
        run: |
          for example in examples/*/*.ino; do
            echo "Compiling $example for board ${{ matrix.board }}"
            arduino-cli compile \
              --fqbn ${{ matrix.board }} \
              --libraries . \
              $example
          done

